---
# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "rdt-uat"
  labels:
    app: minio
    chart: minio-3.4.7
    release: RELEASE-NAME
    heritage: Helm
type: Opaque
data:
  rootUser: "cm9vdHVzZXI="
  rootPassword: "cm9vdHBhc3MxMjM="
